apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbaas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: dbaas
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dbaas
                port:
                  number: 8080